name: black
on:
  push:
    tags:
      - v*
    branches:
      - .*
  pull_request:
    branches:
      - main
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      - name: install-black
        run: python -m pip install black
      - name: black-check
        run: python -m black --check --diff --color -t py311 .
