name: version-check
on:
  pull_request:
    branches:
      - main
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install-deps
        run: python -m pip install semver gitpython
      - name: check-version
        run: |
          git status
          cd internal
          python3 check-version.py
